<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $universidades = [
            'NACIONAL DE MAR DEL PLATA',
            'NACIONAL DE ROSARIO',
            'PONTIFICIA SANTA MARIA DE LOS BUENOS AIRES',
            'PONTIFICIA UNIVERSIDAD JAVERIANA (COLOMBIA)',
            'NACIONAL DE SAN LUIS',
            'PROVINCIAL DE MAR DEL PLATA',
            'NACIONAL DE TUCUMAN',
            'RAFAEL URDANETA',
            'NACIONAL DEL COMAHUE',
            'NACIONAL DEL LITORAL',
            'RICARDO PALMA DEL PERU',
            'DEL SALVADOR',
            'SANTO TOMAS COLOMBIA',
            'PILOTO DE COLOMBIA',
            'SIGLO XXI',
            'PONTIFICA CATOLICA ARGENTINA',
            'PONTIFICA CATOLICA DE PERU',
            'STO TOME',
            'PONTIFICA CATOLICA RIO GRDE DO SUL',
            'UADE',
            'UAI',
            'PONTIFICIA BOLIVARIANA',
            'UCA',
            'PONTIFICIA CAMILLAS (ESPAÑA)',
            'UCES',
            'UNIVERSIDAD COOPERATIVA DE COLOMBIA',
            'NACIONAL DE MAR DEL PLATA',
            'FUNDACION UNIVERSITARIA KONRAD LORENZ (IUNIR)',
            'INSTITUTO UNIVERSITARIO ITALIANO DE ROSARI',
            'ADVENTISTA DEL PLATA',
            'ANTIOQUIA ARGENTINA',
            'ATLANTIDA ARGENTINA',
            'AUSTRAL',
            'AUTOCTONA DE MEXICO',
            'AUTONOMA DE BUCARAMANGA',
            'AUTONOMA DE ENTRE RIOS (UADER)',
            'AUTONOMA DE MADRID',
            'AUTONOMA METROPOLITANA',
            'BARCELONA',
            'BASEL (SUIZA)',
            'CAECE',
            'CATOLICA ANDRES BELLO',
            'CATOLICA ARGENTINA',
            'CATOLICA DE BUENOS AIRES',
            'CATOLICA DE CHILE',
            'CATOLICA DE COLOMBIA',
            'CATOLICA DE COLUMBIA',
            'CATOLICA DE CORDOBA',
            'CATOLICA DE CUYO',
            'CATOLICA DE LA PLATA',
            'CATOLICA DE PERU',
            'CATOLICA DE SALTA',
            'CATOLICA DE SANTA FE',
            'CATOLICA DE SANTIAGO DE GUAYAQUIL',
            'CATOLICA DE SANTIAGO DEL ESTERO',
            'CATOLICA DE TUCUMAN',
            'CIENCIAS EMPRESARIALES Y SOCIALES',
            'COMPLUTENSE DE MADRID',
            'DE BELGRANO',
            'DE CONGRESO MENDOZA',
            'DE DEUSTO',
            'DE FLORES',
            'DE GUADALAJARA',
            'DE LA CUENCA',
            'DEL PLATA',
            'DE LA MARINA MERCANTE',
            'DE LA REPUBLICA',
            'NACIONAL AUTONOMA DE MEXICO',
            'NACIONAL DE ASUNCION',
            'FAVALORO',
            'NACIONAL DE CORDOBA',
            'FILOS Y LETRAS BUENOS AIRES',
            'NACIONAL DE CUYO',
            'FMU SAO PAULO BRASIL',
            'NACIONAL DE EDUCACIÓN A DISTANCIA',
            'FUNDACION BARCELO',
            'NACIONAL DE LA PLATA',
            'FUNDACION UNIVERSITARIA KONRAD LORENZ (IUNIR)',
            'INSTITUTO UNIVERSITARIO ITALIANO DE ROSARI',
            'ADVENTISTA DEL PLATA',
            'ANTIOQUIA ARGENTINA',
            'ATLANTIDA ARGENTINA',
            'AUSTRAL',
            'AUTOCTONA DE MEXICO',
            'AUTONOMA DE BUCARAMANGA',
            'AUTONOMA DE ENTRE RIOS (UADER)',
            'AUTONOMA DE MADRID',
            'AUTONOMA METROPOLITANA',
            'BARCELONA',
            'BASEL (SUIZA)',
            'CAECE',
            'CATOLICA ANDRES BELLO',
            'CATOLICA ARGENTINA',
            'CATOLICA DE BUENOS AIRES',
            'CATOLICA DE CHILE',
            'CATOLICA DE COLOMBIA',
            'CATOLICA DE COLUMBIA',
            'CATOLICA DE CORDOBA',
            'CATOLICA DE CUYO',
            'CATOLICA DE LA PLATA',
            'CATOLICA DE PERU',
            'CATOLICA DE SALTA',
            'CATOLICA DE SANTA FE',
            'CATOLICA DE SANTIAGO DE GUAYAQUIL',
            'CATOLICA DE SANTIAGO DEL ESTERO',
            'CATOLICA DE TUCUMAN',
            'CIENCIAS EMPRESARIALES Y SOCIALES',
            'COMPLUTENSE DE MADRID',
            'DE BELGRANO',
            'DE CONGRESO MENDOZA',
            'DE DEUSTO',
            'DE FLORES',
            'DE GUADALAJARA',
            'DE PALERMO',
            'DE LA MARINA MERCANTE',
            'DE LA REPUBLICA',
            'DE LA CUENCA DEL PLATA',
            'NACIONAL AUTONOMA DE MEXICO',
            'NACIONAL DE ASUNCION',
            'FAVALORO',
            'NACIONAL DE BUENOS AIRES (UBA)',
            'NACIONAL DE CHILE',
            'NACIONAL DE CORDOBA',
            'FAVALORO',
            'NACIONAL DE CUYO',
            'FILOS Y LETRAS BUENOS AIRES',
            'NACIONAL DE CORDOBA',
            'FMU SAO PAULO BRASIL',
            'NACIONAL DE EDUCACIÓN A DISTANCIA',
            'MUSEO SOCIAL ARGENTINO',
            'MAIMONIDES',
            'FUNDACION BARCELO',
            'DEL NORTE',
            'DE MENDOZA',
            'ANTIOQUÍA',
            'NACIONAL DE LA PLATA',
            'NACIONAL DE MAR DEL PLATA',
            'FUNDACION UNIVERSITARIA KONRAD LORENZ (IUNIR)',
            'INSTITUTO UNIVERSITARIO ITALIANO DE ROSARI',
            'ADVENTISTA DEL PLATA',
            'DE SAN BUENAVENTURA',
            'DE LA REPUBLICA ORIENTAL DEL URUGUAY',
            'ANTIOQUIA ARGENTINA',
            'ATLANTIDA ARGENTINA',
            'AUSTRAL',
            'ARGENTINA',
            'AUTOCTONA DE MEXICO',
            'AUTONOMA DE BUCARAMANGA',
            'AUTONOMA DE ENTRE RIOS (UADER)',
            'AUTONOMA DE MADRID',
            'AUTONOMA METROPOLITANA',
            'BARCELONA',
            'BASEL (SUIZA)',
            'CAECE',
            'USAL',
            'CATOLICA ANDRES BELLO',
            'CATOLICA ARGENTINA',
            'CATOLICA DE BUENOS AIRES',
            'CATOLICA DE CHILE',
            'CATOLICA DE COLOMBIA',
            'CATOLICA DE COLUMBIA',
            'CATOLICA DE CORDOBA',
            'CATOLICA DE CUYO',
            'CATOLICA DE LA PLATA',
            'CATOLICA DE PERU',
            'CATOLICA DE SALTA',
            'CATOLICA DE SANTA FE',
            'CATOLICA DE SANTIAGO DE GUAYAQUIL',
            'CATOLICA DE SANTIAGO DEL ESTERO',
            'CATOLICA DE TUCUMAN',
            'CIENCIAS EMPRESARIALES Y SOCIALES',
            'COMPLUTENSE DE MADRID',
            'DE BELGRANO',
            'DE MORON',
            'DE CONGRESO MENDOZA',
            'DE DEUSTO',
            'DE FLORES',
            'DE GUADALAJARA',
            'DE LA CUENCA',
            'DEL PLATA',
            'DE LA MARINA MERCANTE',
            'DE LA REPUBLICA',
            'AUTONOMA DE BUCARAMANGA',
            'VALENCIA',
            'KENNEDY',
            'DE RIO DE JANEIRO',
            'DEL ACONCAGUA',
            'SIN REFERENCIA'
        ];
        foreach ($universidades as $universidad) {
            
            University::create([
                'nombre' => $universidad
            ]);
            
        }
    }
}
